[package]
name = "auxiliary-api"
version = "0.1.0"
edition = "2024"
authors = ["Khenzii <khenzii@khenzii.dev>", "Azteczek"]
repository = "https://github.com/Szpontniki/auxiliary-api"
license = "GPL-3.0-only"

[dependencies]
api_schema = { package = "openapi", path = "./openapi" }
axum = "0.8.9"
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
serde = "1.0.229"
image = "0.25.10"
base64 = "0.23.1"
tower-http = { version = "0.7.1", features = ["cors"] }
diesel = { version = "2.3.13", features = ["chrono", "postgres", "r2d2", "serde_json", "uuid"] }
uuid = { version = "1.27.0", features = ["v4"] }
chrono = { version = "0.4.45", features = ["serde"] }
diesel-derive-enum = { version = "3.0.0-beta.1", features = ["postgres"] }
dotenvy = "0.15.7"
