name: "Checks"
on:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  build-check:
    name: 🗿 Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init the Submodules
        run: git submodule update --init --recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3

      - name: Set up Build Environment
        run: nix develop -c ./generate-api-signatures.sh

      - name: Build
        run: nix develop -c cargo build
